### ISSUE TITLE
[BUG]: Can't choose `http` for YOLOX as a `infer_protocol`

### ISSUE THREAD

**Issue by omihub777** [NVIDIA/nv-ingest#240]
### Version

24.10.1

### Describe the bug.

Hi team,

I would like to use yolox in HTTP, so I set the inference protocol as `http` and the gRPC endpoint as `""` in `docker-compose.yaml` for yolox:
```yaml
nv-ingest-ms-runtime:
  ...
  environment:
      - YOLOX_INFER_PROTOCOL=http
      - YOLOX_HTTP_ENDPOINT=http://yolox:8000/v1/infer
      - YOLOX_GRPC_ENDPOINT=""
```

Although nv-ingest server creates a inference client for pdf extraction, the current implementation doesn't seem to pass `infer_protocol`:
https://github.com/NVIDIA/nv-ingest/blob/00abf4750a7bed990c16403c8d14ca10fbd63bc1/src/nv_ingest/extraction_workflows/pdf/pdfium_helper.py#L134

Thus, `create_inference_client` returns `None` because both of `infer_protocol` and `grpc_endpoint` are `None` in the following condition:
https://github.com/NVIDIA/nv-ingest/blob/00abf4750a7bed990c16403c8d14ca10fbd63bc1/src/nv_ingest/util/nim/helpers.py#L58

Feel free to correct me if I am missing something. Thank you!

### Minimum reproducible example

```shell

```

### Relevant log output

```shell

```
