### ISSUE TITLE
[BUG]: `nv_ingest_client` Conda package does not depend on pymilvus

### ISSUE THREAD

**Issue by dagardner-nv** [NVIDIA/nv-ingest#450]
### Version

2025.02.10.dev0

### Which installation method(s) does this occur on?

Source

### Describe the bug.

I created my Conda env with this yaml:
```yaml
channels:
- conda-forge
- rapidsai
- rapidsai-nightly
- nvidia
- nvidia/label/dev
- pytorch
dependencies:
- nv_ingest
- nv_ingest_client
- python=3.10
name: nv_ingest_test
```

However I get a pymilvus import error when importing the client:
```bash
conda env create --solver=libmamba --name nv_ingest_test --file examples/nv_ingest/test.yaml
conda activate nv_ingest_test
python -c "from nv_ingest_client.client import NvIngestClient"
```

### Minimum reproducible example

```shell
conda env create --solver=libmamba --name nv_ingest_test --file examples/nv_ingest/test.yaml
conda activate nv_ingest_test
python -c "from nv_ingest_client.client import NvIngestClient"
```

### Relevant log output

```shell
ModuleNotFoundError: No module named 'pymilvus'
```
